"""Add notion ID for elements

Revision ID: 385f5b26b821
Revises: 6398e195c99b
Create Date: 2023-05-08 23:23:19.995884

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "385f5b26b821"
down_revision = "6398e195c99b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("elements", sa.Column("notion_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_elements_notion_id"), "elements", ["notion_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_elements_notion_id"), table_name="elements")
    op.drop_column("elements", "notion_id")
    # ### end Alembic commands ###
