"""Add tables for caching content

Revision ID: 6398e195c99b
Revises: 7c2fa1ca458f
Create Date: 2023-05-08 19:59:02.968154

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6398e195c99b"
down_revision = "7c2fa1ca458f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_edited", sa.DateTime(), nullable=True),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_elements_id"), "elements", ["id"], unique=False)
    op.create_table(
        "booleans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("element_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_booleans_id"), "booleans", ["id"], unique=False)
    op.create_table(
        "dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.DateTime(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("element_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dates_id"), "dates", ["id"], unique=False)
    op.create_table(
        "multis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("element_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_multis_id"), "multis", ["id"], unique=False)
    op.create_table(
        "numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("element_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_numbers_id"), "numbers", ["id"], unique=False)
    op.create_table(
        "strings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("element_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strings_id"), "strings", ["id"], unique=False)
    op.create_table(
        "stringparts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("multiattribute_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["multiattribute_id"],
            ["multis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stringparts_id"), "stringparts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stringparts_id"), table_name="stringparts")
    op.drop_table("stringparts")
    op.drop_index(op.f("ix_strings_id"), table_name="strings")
    op.drop_table("strings")
    op.drop_index(op.f("ix_numbers_id"), table_name="numbers")
    op.drop_table("numbers")
    op.drop_index(op.f("ix_multis_id"), table_name="multis")
    op.drop_table("multis")
    op.drop_index(op.f("ix_dates_id"), table_name="dates")
    op.drop_table("dates")
    op.drop_index(op.f("ix_booleans_id"), table_name="booleans")
    op.drop_table("booleans")
    op.drop_index(op.f("ix_elements_id"), table_name="elements")
    op.drop_table("elements")
    # ### end Alembic commands ###
