"""Database creation

Revision ID: 7c2fa1ca458f
Revises:
Create Date: 2023-05-01 21:27:59.019858

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7c2fa1ca458f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_integrations_id"), "integrations", ["id"], unique=False)
    op.create_index(op.f("ix_integrations_token"), "integrations", ["token"], unique=True)
    op.create_table(
        "tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.String(), nullable=True),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tables_id"), "tables", ["id"], unique=False)
    op.create_index(op.f("ix_tables_table_id"), "tables", ["table_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tables_table_id"), table_name="tables")
    op.drop_index(op.f("ix_tables_id"), table_name="tables")
    op.drop_table("tables")
    op.drop_index(op.f("ix_integrations_token"), table_name="integrations")
    op.drop_index(op.f("ix_integrations_id"), table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
