"""Cascade delete attributes of an element

Revision ID: 954c12461099
Revises: bcd270175818
Create Date: 2023-05-10 19:30:04.329876

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "954c12461099"
down_revision = "bcd270175818"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booleans", schema=None) as batch_op:
        batch_op.drop_constraint("fk_booleans_element_id_elements", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_booleans_element_id_elements"), "elements", ["element_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("dates", schema=None) as batch_op:
        batch_op.drop_constraint("fk_dates_element_id_elements", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_dates_element_id_elements"), "elements", ["element_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("multis", schema=None) as batch_op:
        batch_op.drop_constraint("fk_multis_element_id_elements", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_multis_element_id_elements"), "elements", ["element_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.drop_constraint("fk_numbers_element_id_elements", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_numbers_element_id_elements"), "elements", ["element_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("strings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_strings_element_id_elements", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_strings_element_id_elements"), "elements", ["element_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strings", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_strings_element_id_elements"), type_="foreignkey")
        batch_op.create_foreign_key("fk_strings_element_id_elements", "elements", ["element_id"], ["id"])

    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_numbers_element_id_elements"), type_="foreignkey")
        batch_op.create_foreign_key("fk_numbers_element_id_elements", "elements", ["element_id"], ["id"])

    with op.batch_alter_table("multis", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_multis_element_id_elements"), type_="foreignkey")
        batch_op.create_foreign_key("fk_multis_element_id_elements", "elements", ["element_id"], ["id"])

    with op.batch_alter_table("dates", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_dates_element_id_elements"), type_="foreignkey")
        batch_op.create_foreign_key("fk_dates_element_id_elements", "elements", ["element_id"], ["id"])

    with op.batch_alter_table("booleans", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_booleans_element_id_elements"), type_="foreignkey")
        batch_op.create_foreign_key("fk_booleans_element_id_elements", "elements", ["element_id"], ["id"])

    # ### end Alembic commands ###
